use anyhow::{bail, Context, Result};
use clap::{Parser, Subcommand};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Parser, Debug)]
#[command(
    name = "synapse",
    version,
    about = "Synapse admin CLI",
    long_about = "Manage Synapse admin reconciliation commands.\n\nUse the nested reconciliation subcommands to list stored reports, inspect a single report, or run a fresh reconciliation against the API.",
    arg_required_else_help = true
)]
struct Cli {
    /// Base URL of the Synapse API.
    #[arg(
        long,
        value_name = "URL",
        default_value = "http://127.0.0.1:3000"
    )]
    base_url: String,

    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Admin operations exposed by the Synapse API.
    #[command(
        about = "Admin operations",
        long_about = "Admin operations exposed by the Synapse API."
    )]
    Admin(AdminCommands),
}

#[derive(Subcommand, Debug)]
enum AdminCommands {
    /// Reconciliation reports and runs.
    #[command(
        about = "Reconciliation reports",
        long_about = "List, inspect, or run reconciliation reports through the admin API."
    )]
    Reconciliation(ReconciliationCommands),
}

#[derive(Subcommand, Debug)]
enum ReconciliationCommands {
    #[command(
        about = "List reconciliation reports",
        long_about = "List reconciliation reports generated by the admin API.\n\nRequired flags: none.\nOptional flags:\n  --limit <LIMIT>   Maximum number of reports to return (default: 20).\n  --offset <OFFSET>  Number of reports to skip before returning results (default: 0)."
    )]
    Reports {
        /// Maximum number of reports to return.
        #[arg(long, value_name = "LIMIT", default_value_t = 20)]
        limit: u32,

        /// Number of reports to skip before returning results.
        #[arg(long, value_name = "OFFSET", default_value_t = 0)]
        offset: u32,
    },

    #[command(
        about = "Show a reconciliation report",
        long_about = "Fetch one reconciliation report by UUID and print the full response body.\n\nRequired flags:\n  <REPORT_ID>       UUID of the report to fetch.\nOptional flags: none."
    )]
    Report {
        /// UUID of the reconciliation report to fetch.
        #[arg(value_name = "REPORT_ID")]
        report_id: Uuid,
    },

    #[command(
        about = "Run a reconciliation report",
        long_about = "Run a reconciliation pass for one Stellar account and persist the result.\n\nRequired flags:\n  --account <ACCOUNT>      Stellar account to reconcile.\nOptional flags:\n  --period-hours <HOURS>   Hours of history to include (default: 24)."
    )]
    Run {
        /// Stellar account to reconcile.
        #[arg(long, value_name = "ACCOUNT")]
        account: String,

        /// Hours of history to include.
        #[arg(long, value_name = "HOURS")]
        period_hours: Option<u32>,
    },
}

#[derive(Debug, Deserialize)]
struct ListReportsResponse {
    reports: Vec<ReportSummary>,
    total: i64,
    limit: i32,
    offset: i32,
}

#[derive(Debug, Deserialize)]
struct ReportSummary {
    id: Uuid,
    generated_at: String,
    period_start: String,
    period_end: String,
    total_db_transactions: i32,
    total_chain_payments: i32,
    missing_on_chain_count: i32,
    orphaned_payments_count: i32,
    amount_mismatches_count: i32,
    has_discrepancies: bool,
}

#[derive(Debug, Deserialize)]
struct RunResponse {
    message: String,
    report: ReportSummary,
}

#[derive(Debug, Serialize)]
struct RunRequest<'a> {
    account: &'a str,
    period_hours: Option<u32>,
}

#[tokio::main]
async fn main() -> Result<()> {
    let cli = Cli::parse();
    let client = reqwest::Client::new();
    let base_url = cli.base_url.trim_end_matches('/').to_string();

    match cli.command {
        Commands::Admin(admin) => match admin {
            AdminCommands::Reconciliation(command) => {
                handle_reconciliation(&client, &base_url, command).await?
            }
        },
    }

    Ok(())
}

async fn handle_reconciliation(
    client: &reqwest::Client,
    base_url: &str,
    command: ReconciliationCommands,
) -> Result<()> {
    match command {
        ReconciliationCommands::Reports { limit, offset } => {
            let url = format!("{base_url}/admin/reconciliation/reports?limit={limit}&offset={offset}");
            let response = send_json_request::<ListReportsResponse>(client.get(url)).await?;
            print_reports(response);
        }
        ReconciliationCommands::Report { report_id } => {
            let url = format!("{base_url}/admin/reconciliation/reports/{report_id}");
            let response = send_text_request(client.get(url)).await?;
            let json: serde_json::Value =
                serde_json::from_str(&response).context("failed to parse report JSON")?;
            println!("{}", serde_json::to_string_pretty(&json)?);
        }
        ReconciliationCommands::Run {
            account,
            period_hours,
        } => {
            let url = format!("{base_url}/admin/reconciliation/run");
            let response = send_json_request::<RunResponse>(
                client.post(url).json(&RunRequest {
                    account: &account,
                    period_hours,
                }),
            )
            .await?;
            print_run_response(response);
        }
    }

    Ok(())
}

async fn send_json_request<T>(request: reqwest::RequestBuilder) -> Result<T>
where
    T: for<'de> Deserialize<'de>,
{
    let response = request.send().await.context("request failed")?;
    let status = response.status();
    let body = response.text().await.context("failed to read response body")?;

    if !status.is_success() {
        bail!("server returned {status}: {body}");
    }

    serde_json::from_str(&body).context("failed to parse response JSON")
}

async fn send_text_request(request: reqwest::RequestBuilder) -> Result<String> {
    let response = request.send().await.context("request failed")?;
    let status = response.status();
    let body = response.text().await.context("failed to read response body")?;

    if !status.is_success() {
        bail!("server returned {status}: {body}");
    }

    Ok(body)
}

fn print_reports(response: ListReportsResponse) {
    println!(
        "Reports: {} total (showing {} from offset {}, limit {})",
        response.total,
        response.reports.len(),
        response.offset,
        response.limit
    );

    if response.reports.is_empty() {
        println!("No reconciliation reports found");
        return;
    }

    for report in response.reports {
        println!(
            "- {} | generated {} | period {} to {} | db {} | chain {} | discrepancies: {}",
            report.id,
            report.generated_at,
            report.period_start,
            report.period_end,
            report.total_db_transactions,
            report.total_chain_payments,
            yes_no(report.has_discrepancies)
        );
    }
}

fn print_run_response(response: RunResponse) {
    let report = response.report;

    println!("{}", response.message);
    println!();
    println!("Report ID: {}", report.id);
    println!("Generated: {}", report.generated_at);
    println!(
        "Period: {} to {}",
        report.period_start, report.period_end
    );
    println!();
    println!("Summary:");
    println!("  Database transactions: {}", report.total_db_transactions);
    println!("  Chain payments: {}", report.total_chain_payments);
    println!("  Missing on chain: {}", report.missing_on_chain_count);
    println!("  Orphaned payments: {}", report.orphaned_payments_count);
    println!("  Amount mismatches: {}", report.amount_mismatches_count);
    println!("  Has discrepancies: {}", yes_no(report.has_discrepancies));
}

fn yes_no(value: bool) -> &'static str {
    if value { "yes" } else { "no" }
}
